# Dockerfile_kafka

# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Run consumer.py when the container launches
CMD ["python", "notifications_reports_app/python expenses_notification_consumer.py"]
CMD ["python", "notifications_reports_app/python expenses_reports_consumer.py"]
